name: Build and tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest, windows-latest
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.7.0

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint project
        run: pnpm lint

      - name: Test project
        run: pnpm test

      - name: Build project
        run: pnpm build
